LEXICON_BUTTONS_RU: dict[str: str] = {
    'new_session': 'Загрузить новый файл 🔥',
    'buy_subscription': 'Приобрести подписку 💳',
    'cancel_subscription': 'Отменить подписку 🚫',
    'sure_cancel_subscription': 'Да, точно отменить ✅',
    'source_statistic': 'Статистика источников заходов 📊',
    'spam_menu': 'Рассылка сообщений 📨',
    'source_with_subscription': 'Статистика источников подписок 📈',
    'buy_monthly_subscription': 'Месячная подписка: 349 рублей в месяц 📅',
    'buy_annual_subscription': 'Годовая подписка: 1990 рублей в год 📆',
    'buy_weekly_subscription': 'Недельная подписка: 149 рублей в неделю 🗓️',
    'restart_bot': 'Перезагрузить бота 🔄',
    'subscription': 'Подписка 💳',
    'support': 'Поддержка 🆘',
    'you_can_ask': 'Можно задать вопросы по тексту ⚡',
    'you_can_ask_2': 'Задать вопросы по содержанию 🔎',
    'renew_subscription': 'Возобновить подписку 🔄',
    'give_subscription': 'Выдать подписку 🎁',
    'change_llm_model': 'Модель ИИ 🤖',
    'specify_language': 'Функция уточнения языка 🌐',
    'change_language': 'Изменить язык 🌍',
    'back': '🔙',
    'ask_language': 'Спрашивать язык: {0}',
    'continue_without_language': 'Продолжить без уточнения языка',
    'main_menu': 'Главное меню 🏠',
    'faq': 'FAQ ❓',
    'yes_specify_lang': 'Спрашивать язык ✅',
    'no_specify_lang': 'Не спрашивать язык ❌',
    'settings': 'Настройки ⚙️',
    'spam_all': 'Всем пользователям',
    'spam_subscribed': 'Пользователям с подпиской',
    'spam_unsubscribed': 'Пользователям без подписки',
    'payments_with_subscription': 'Cтатистика источников оплат'
}

LEXICON_BUTTONS_EN: dict[str: str] = {
    'new_session': 'Transcribe new audio/video 🔥',
    'buy_subscription': 'Buy a subscription 💳',
    'cancel_subscription': 'Cancel subscription 🚫',
    'sure_cancel_subscription': 'Yes, definitely cancel ✅',
    'source_statistic': 'Traffic source statistics 📊',
    'spam_menu': 'Send messages 📨',
    'source_with_subscription': 'Subscription source statistics 📈',
    'buy_monthly_subscription': 'Monthly subscription: 349 rubles per month 📅',
    'buy_annual_subscription': 'Annual subscription: 1990 rubles per year 📆',
    'buy_weekly_subscription': 'Weekly subscription: 149 rubles per week 🗓️',
    'restart_bot': 'Restart Bot 🔄',
    'subscription': 'Subscription  📄',
    'support': 'Support 🆘',
    'you_can_ask': 'You can ask questions about the text ⚡',
    'you_can_ask_2': 'Ask questions about the content 🔎',
    'renew_subscription': 'Renew subscription 🔄',
    'give_subscription': 'Give a subscription 🎁',
    'change_llm_model': 'AI Model 🤖',
    'specify_language': 'Language specification function 🌐',
    'change_language': 'Change language 🌍',
    'back': '🔙',
    'ask_language': 'Ask for language: {0}',
    'continue_without_language': 'Continue without specifying language',
    'main_menu': 'Main menu 🏠',
    'faq': 'FAQ ❓',
    'yes_specify_lang': 'Ask for language ✅',
    'no_specify_lang': 'Don\'t ask for language ❌',
    'settings': 'Settings ⚙️',
    'spam_all': 'All users',
    'spam_subscribed': 'Subscribed users',
    'spam_unsubscribed': 'Unsubscribed users',
}

LEXICON_COMMANDS: dict[str: str] = {
    'start': 'Главное меню | Home',
    'subscription': 'Купить подписку | Get subscription',
    'referral': 'Реферальная программа | Referral Program',
    'settings': 'Настройки | Settings',
    'support': 'Поддержка | Support',
    # 'faq': 'Часто задаваемые вопросы',
}

language_codes = {
    'Bulgarian': ['bg'],
    'Catalan': ['ca'],
    'Chinese (Mandarin, Simplified)': ['zh', 'zh-CN', 'zh-Hans'],
    'Chinese (Mandarin, Traditional)': ['zh-TW', 'zh-Hant'],
    'Chinese (Cantonese, Traditional)': ['zh-HK'],
    'Czech': ['cs'],
    'Danish': ['da', 'da-DK'],
    'Dutch': ['nl'],
    'English': ['en', 'en-US', 'en-AU', 'en-GB', 'en-NZ', 'en-IN'],
    'Estonian': ['et'],
    'Finnish': ['fi'],
    'Flemish': ['nl-BE'],
    'French': ['fr', 'fr-CA'],
    'German': ['de'],
    'German (Switzerland)': ['de-CH'],
    'Greek': ['el'],
    'Hindi': ['hi'],
    'Hungarian': ['hu'],
    'Indonesian': ['id'],
    'Italian': ['it'],
    'Japanese': ['ja'],
    'Korean': ['ko', 'ko-KR'],
    'Latvian': ['lv'],
    'Lithuanian': ['lt'],
    'Malay': ['ms'],
    'Norwegian': ['no'],
    'Polish': ['pl'],
    'Portuguese': ['pt', 'pt-BR', 'pt-PT'],
    'Romanian': ['ro'],
    'Russian': ['ru'],
    'Slovak': ['sk'],
    'Spanish': ['es', 'es-419'],
    'Swedish': ['sv', 'sv-SE'],
    'Thai': ['th', 'th-TH'],
    'Turkish': ['tr'],
    'Ukrainian': ['uk'],
    'Vietnamese': ['vi']
}

language_codes_whisper = {
    'Afrikaans': ['af'],
    'Albanian': ['sq'],
    'Amharic': ['am'],
    'Arabic': ['ar'],
    'Armenian': ['hy'],
    'Assamese': ['as'],
    'Azerbaijani': ['az'],
    'Bashkir': ['ba'],
    'Basque': ['eu'],
    'Belarusian': ['be'],
    'Bengali': ['bn'],
    'Bosnian': ['bs'],
    'Breton': ['br'],
    'Bulgarian': ['bg'],
    'Burmese/Myanmar': ['my'],
    'Cantonese': ['yue'],
    'Castilian': ['es'],  # alias for Spanish
    'Catalan/Valencian': ['ca'],
    'Chinese (Mandarin)': ['zh', 'zh-CN', 'zh-Hans'],
    'Chinese (Traditional)': ['zh-TW', 'zh-Hant'],
    'Chinese (Cantonese, Traditional)': ['zh-HK'],
    'Croatian': ['hr'],
    'Czech': ['cs'],
    'Danish': ['da', 'da-DK'],
    'Dutch/Flemish': ['nl', 'nl-BE'],
    'English': ['en', 'en-US', 'en-AU', 'en-GB', 'en-NZ', 'en-IN'],
    'Estonian': ['et'],
    'Faroese': ['fo'],
    'Finnish': ['fi'],
    'French': ['fr', 'fr-CA'],
    'Galician': ['gl'],
    'Georgian': ['ka'],
    'German': ['de'],
    'German (Switzerland)': ['de-CH'],
    'Greek': ['el'],
    'Gujarati': ['gu'],
    'Haitian/Haitian Creole': ['ht'],
    'Hausa': ['ha'],
    'Hawaiian': ['haw'],
    'Hebrew': ['he'],
    'Hindi': ['hi'],
    'Hungarian': ['hu'],
    'Icelandic': ['is'],
    'Indonesian': ['id'],
    'Italian': ['it'],
    'Japanese': ['ja'],
    'Javanese': ['jw'],
    'Kannada': ['kn'],
    'Kazakh': ['kk'],
    'Khmer': ['km'],
    'Korean': ['ko', 'ko-KR'],
    'Lao': ['lo'],
    'Latin': ['la'],
    'Latvian': ['lv'],
    'Lingala': ['ln'],
    'Lithuanian': ['lt'],
    'Luxembourgish/Letzeburgesch': ['lb'],
    'Macedonian': ['mk'],
    'Malagasy': ['mg'],
    'Malay': ['ms'],
    'Malayalam': ['ml'],
    'Maltese': ['mt'],
    'Maori': ['mi'],
    'Marathi': ['mr'],
    'Moldavian/Moldovan': ['ro'],  # alias for Romanian
    'Mongolian': ['mn'],
    'Nepali': ['ne'],
    'Norwegian': ['no'],
    'Nynorsk': ['nn'],
    'Occitan': ['oc'],
    'Panjabi/Punjabi': ['pa'],
    'Pashto/Pushto': ['ps'],
    'Persian': ['fa'],
    'Polish': ['pl'],
    'Portuguese': ['pt', 'pt-BR', 'pt-PT'],
    'Romanian': ['ro'],
    'Russian': ['ru'],
    'Sanskrit': ['sa'],
    'Serbian': ['sr'],
    'Shona': ['sn'],
    'Sindhi': ['sd'],
    'Sinhala/Sinhalese': ['si'],
    'Slovak': ['sk'],
    'Slovenian': ['sl'],
    'Somali': ['so'],
    'Spanish': ['es', 'es-419'],
    'Sundanese': ['su'],
    'Swahili': ['sw'],
    'Swedish': ['sv', 'sv-SE'],
    'Tagalog': ['tl'],
    'Tajik': ['tg'],
    'Tamil': ['ta'],
    'Tatar': ['tt'],
    'Telugu': ['te'],
    'Thai': ['th', 'th-TH'],
    'Tibetan': ['bo'],
    'Turkish': ['tr'],
    'Turkmen': ['tk'],
    'Ukrainian': ['uk'],
    'Urdu': ['ur'],
    'Uzbek': ['uz'],
    'Vietnamese': ['vi'],
    'Welsh': ['cy'],
    'Yiddish': ['yi'],
    'Yoruba': ['yo']
}